# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
- package-ecosystem: composer
  directories:
    - "/"
    - "/vendor-bin/csfixer"
    - "/vendor-bin/phpunit"
    - "/vendor-bin/psalm"
    - "/vendor-bin/rector"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies
  cooldown:
    default-days: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
  - 3. to review
  - dependencies
  cooldown:
    default-days: 10
