kind: pipeline
name: check-app-compatbility2

steps:
  - name: check-app-compatbility
    image: nextcloudci/php5.6:php5.6-3
    environment:
      - APP_NAME=guests
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: integration

steps:
  - name: integration
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=guests
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Run integration
      - cd apps/$APP_NAME/
      - cd tests/integration
      - bash ./run.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
